services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - neo4j
  
  neo4j:
    image: neo4j
    environment:
      - NEO4J_AUTH=neo4j/crowdstop
    ports:
      - "7474:7474"
      - "7687:7687"

